
import { useState } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { generateId } from '@/lib/utils';
import { GeneratedLicense } from '@/types';
import { CheckCircle, Copy, Key } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

const LicenseGenerator = () => {
  const { user } = useAuth();
  const { toast } = useToast();
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedLicense, setGeneratedLicense] = useState<GeneratedLicense | null>(null);
  
  const [formData, setFormData] = useState({
    name: '',
    publisher: '2lecybersec.com',
    licenseType: 'full' as 'trial' | 'full' | 'enterprise',
    seats: 1,
    duration: 365,
    department: '',
    notes: ''
  });

  const generateLicenseKey = (name: string, type: string): string => {
    const timestamp = Date.now().toString(36);
    const random = Math.random().toString(36).substring(2, 8).toUpperCase();
    const prefix = type === 'trial' ? 'TRL' : type === 'enterprise' ? 'ENT' : 'STD';
    const nameCode = name.substring(0, 3).toUpperCase().replace(/[^A-Z]/g, 'X');
    
    return `${prefix}-${nameCode}-${random}-${timestamp.toUpperCase()}`;
  };

  const handleGenerate = async () => {
    if (!formData.name.trim()) {
      toast({
        title: "Erro",
        description: "Nome do software é obrigatório",
        variant: "destructive"
      });
      return;
    }

    setIsGenerating(true);

    // Simulate license generation process
    await new Promise(resolve => setTimeout(resolve, 2000));

    const licenseKey = generateLicenseKey(formData.name, formData.licenseType);
    const expirationDate = formData.duration ? 
      new Date(Date.now() + formData.duration * 24 * 60 * 60 * 1000).toISOString() : 
      undefined;

    const newLicense: GeneratedLicense = {
      id: generateId(),
      name: formData.name,
      publisher: formData.publisher,
      purchaseDate: new Date().toISOString(),
      expirationDate,
      seats: formData.seats,
      usedSeats: 0,
      notes: formData.notes,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      isGenerated: true,
      generatedBy: user?.id || '',
      watermark: 'Generated by 2lecybersec.com - Rack-IT-All System',
      licenseType: formData.licenseType,
      duration: formData.duration,
      licenseKey
    };

    setGeneratedLicense(newLicense);
    setIsGenerating(false);

    toast({
      title: "Licença gerada com sucesso!",
      description: `Licença ${formData.licenseType} criada para ${formData.name}`,
    });

    // Reset form
    setFormData({
      name: '',
      publisher: '2lecybersec.com',
      licenseType: 'full',
      seats: 1,
      duration: 365,
      department: '',
      notes: ''
    });
  };

  const copyLicenseKey = () => {
    if (generatedLicense?.licenseKey) {
      navigator.clipboard.writeText(generatedLicense.licenseKey);
      toast({
        title: "Copiado!",
        description: "Chave da licença copiada para a área de transferência",
      });
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Gerador de Licenças</h1>
        <p className="text-muted-foreground">
          Área restrita para administradores - Gere licenças personalizadas
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Key className="w-5 h-5" />
              Gerar Nova Licença
            </CardTitle>
            <CardDescription>
              Preencha os dados para gerar uma nova licença do sistema
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="name">Nome do Software *</Label>
              <Input
                id="name"
                placeholder="Ex: Rack-IT-All Enterprise"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="publisher">Publicador</Label>
              <Input
                id="publisher"
                value={formData.publisher}
                onChange={(e) => setFormData({ ...formData, publisher: e.target.value })}
                disabled
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="licenseType">Tipo de Licença</Label>
              <Select 
                value={formData.licenseType} 
                onValueChange={(value: 'trial' | 'full' | 'enterprise') => 
                  setFormData({ ...formData, licenseType: value })
                }
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="trial">Trial (Avaliação)</SelectItem>
                  <SelectItem value="full">Full (Completa)</SelectItem>
                  <SelectItem value="enterprise">Enterprise (Empresarial)</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="seats">Número de Assentos</Label>
                <Input
                  id="seats"
                  type="number"
                  min="1"
                  value={formData.seats}
                  onChange={(e) => setFormData({ ...formData, seats: parseInt(e.target.value) || 1 })}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="duration">Duração (dias)</Label>
                <Input
                  id="duration"
                  type="number"
                  min="1"
                  value={formData.duration}
                  onChange={(e) => setFormData({ ...formData, duration: parseInt(e.target.value) || 365 })}
                />
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="department">Departamento</Label>
              <Input
                id="department"
                placeholder="Ex: TI, Financeiro, RH"
                value={formData.department}
                onChange={(e) => setFormData({ ...formData, department: e.target.value })}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="notes">Observações</Label>
              <Textarea
                id="notes"
                placeholder="Observações adicionais..."
                value={formData.notes}
                onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
              />
            </div>

            <Button 
              onClick={handleGenerate} 
              className="w-full"
              disabled={isGenerating}
            >
              {isGenerating ? 'Gerando...' : 'Gerar Licença'}
            </Button>
          </CardContent>
        </Card>

        {generatedLicense && (
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-green-600">
                <CheckCircle className="w-5 h-5" />
                Licença Gerada
              </CardTitle>
              <CardDescription>
                Licença criada com sucesso - Guarde essas informações
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-3 p-4 bg-gray-50 rounded-lg">
                <div>
                  <Label className="text-sm font-medium">Nome:</Label>
                  <p className="text-sm">{generatedLicense.name}</p>
                </div>
                
                <div>
                  <Label className="text-sm font-medium">Tipo:</Label>
                  <p className="text-sm capitalize">{generatedLicense.licenseType}</p>
                </div>
                
                <div>
                  <Label className="text-sm font-medium">Chave da Licença:</Label>
                  <div className="flex items-center gap-2">
                    <code className="text-sm bg-white p-2 rounded border flex-1 break-all">
                      {generatedLicense.licenseKey}
                    </code>
                    <Button size="sm" variant="outline" onClick={copyLicenseKey}>
                      <Copy className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
                
                <div>
                  <Label className="text-sm font-medium">Assentos:</Label>
                  <p className="text-sm">{generatedLicense.seats}</p>
                </div>
                
                <div>
                  <Label className="text-sm font-medium">Validade:</Label>
                  <p className="text-sm">
                    {generatedLicense.expirationDate 
                      ? new Date(generatedLicense.expirationDate).toLocaleDateString()
                      : 'Perpétua'
                    }
                  </p>
                </div>
              </div>

              <Alert>
                <AlertDescription className="text-sm">
                  <strong>Marca d'água:</strong> {generatedLicense.watermark}
                </AlertDescription>
              </Alert>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
};

export default LicenseGenerator;
