// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvlpnzffmxbqoxqmwsvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2bHBuemZmbXhicW94cW13c3ZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1OTY2NzIsImV4cCI6MjA2NTE3MjY3Mn0.Bi7T-RF0BNAvtsXBW4Np7Qa9v3JlUDxYOImbmLE13xE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);